= {lab_name}

Use the Portworx Data Platform to manage persistant storage in an OpenShift 4 cluster.

Portworx is the #1 leader in Kubernetes storage and data management. Together, Portworx and Red Hat® OpenShift® Container Platform help you operate, scale, and secure Kubernetes and application databases anywhere with just a few clicks.

This hands-on demo provides a Portworx deployment on OpenShift Container Platform and covers the following topics:

* Overview of OpenShift Container Platform interaction

* Portworx OpenShift Operator

* Application deployment for demos

* Use cases demos

=== Lab Access

The terminal window to your right has the `oc` command we will use during the lab already installed, but we need to login to the cluster

Use this command to login to the cluster:

[,bash,role="execute",subs="attributes"]
----
oc login {openshift_api_url} -u {openshift_cluster_admin_username}  -p {openshift_cluster_admin_password}
oc project default
----

NOTE:  The lab guide is available in Asciidoc on link:https://github.com/PureStorage-OpenConnect/pxe-rhdp-lab/tree/main/content/modules/ROOT/pages[Github] if you wish to save it for future reference.
